import type {
  User,
  Task,
  Project,
  Product,
  Order,
  Invoice,
  Transaction,
  Notification,
  Alert,
  Activity,
  SupportTicket,
  FAQ,
  Article,
  Category,
  DashboardStats,
} from './types';

// ============================================================================
// USERS (8)
// ============================================================================
export const users: User[] = [
  {
    id: 'usr-001',
    email: 'admin@example.com',
    password: 'admin123',
    name: 'Sarah Chen',
    role: 'admin',
    phone: '+1 (555) 101-2001',
    department: 'Engineering',
    status: 'active',
    avatar: '/avatars/sarah.jpg',
    bio: 'Full-stack engineer with 10+ years of experience leading distributed teams.',
    createdAt: '2024-01-15T09:00:00Z',
    lastLogin: '2026-03-03T14:22:00Z',
  },
  {
    id: 'usr-002',
    email: 'james.wilson@company.com',
    password: 'james123',
    name: 'James Wilson',
    role: 'manager',
    phone: '+1 (555) 101-2002',
    department: 'Product',
    status: 'active',
    avatar: '/avatars/james.jpg',
    bio: 'Product manager focused on user-centric design and agile methodologies.',
    createdAt: '2024-02-10T10:30:00Z',
    lastLogin: '2026-03-02T09:15:00Z',
  },
  {
    id: 'usr-003',
    email: 'maria.garcia@company.com',
    password: 'maria123',
    name: 'Maria Garcia',
    role: 'user',
    phone: '+1 (555) 101-2003',
    department: 'Design',
    status: 'active',
    avatar: '/avatars/maria.jpg',
    bio: 'UI/UX designer passionate about accessibility and inclusive design.',
    createdAt: '2024-03-05T08:00:00Z',
    lastLogin: '2026-03-03T11:40:00Z',
  },
  {
    id: 'usr-004',
    email: 'david.kim@company.com',
    password: 'david123',
    name: 'David Kim',
    role: 'user',
    phone: '+1 (555) 101-2004',
    department: 'Engineering',
    status: 'active',
    avatar: '/avatars/david.jpg',
    bio: 'Backend developer specializing in microservices and cloud architecture.',
    createdAt: '2024-04-20T11:00:00Z',
    lastLogin: '2026-03-01T16:30:00Z',
  },
  {
    id: 'usr-005',
    email: 'emily.johnson@company.com',
    password: 'emily123',
    name: 'Emily Johnson',
    role: 'manager',
    phone: '+1 (555) 101-2005',
    department: 'Marketing',
    status: 'active',
    avatar: '/avatars/emily.jpg',
    bio: 'Marketing lead with expertise in growth strategy and brand development.',
    createdAt: '2024-05-12T09:30:00Z',
    lastLogin: '2026-03-03T08:50:00Z',
  },
  {
    id: 'usr-006',
    email: 'alex.thompson@company.com',
    password: 'alex123',
    name: 'Alex Thompson',
    role: 'user',
    phone: '+1 (555) 101-2006',
    department: 'Engineering',
    status: 'inactive',
    avatar: '/avatars/alex.jpg',
    bio: 'Frontend developer with a focus on React and performance optimization.',
    createdAt: '2024-06-01T10:00:00Z',
    lastLogin: '2025-12-15T13:20:00Z',
  },
  {
    id: 'usr-007',
    email: 'rachel.patel@company.com',
    password: 'rachel123',
    name: 'Rachel Patel',
    role: 'user',
    phone: '+1 (555) 101-2007',
    department: 'QA',
    status: 'active',
    avatar: '/avatars/rachel.jpg',
    bio: 'Quality assurance engineer dedicated to automated testing and CI/CD pipelines.',
    createdAt: '2024-07-18T08:45:00Z',
    lastLogin: '2026-03-02T17:10:00Z',
  },
  {
    id: 'usr-008',
    email: 'michael.brown@company.com',
    password: 'michael123',
    name: 'Michael Brown',
    role: 'admin',
    phone: '+1 (555) 101-2008',
    department: 'Operations',
    status: 'suspended',
    avatar: '/avatars/michael.jpg',
    bio: 'Operations manager overseeing infrastructure and DevOps initiatives.',
    createdAt: '2024-01-08T07:30:00Z',
    lastLogin: '2026-01-10T10:00:00Z',
  },
];

// ============================================================================
// PROJECTS (6)
// ============================================================================
export const projects: Project[] = [
  {
    id: 'proj-001',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern UI/UX, improved performance, and mobile-first responsive design.',
    status: 'active',
    progress: 65,
    budget: 150000,
    spent: 97500,
    startDate: '2025-06-01',
    endDate: '2026-06-30',
    teamMembers: ['usr-001', 'usr-003', 'usr-004', 'usr-006'],
    milestones: [
      { id: 'ms-001', title: 'Design Mockups Approved', dueDate: '2025-08-15', completed: true },
      { id: 'ms-002', title: 'Frontend Development Complete', dueDate: '2025-12-01', completed: true },
      { id: 'ms-003', title: 'Backend Integration', dueDate: '2026-03-15', completed: false },
      { id: 'ms-004', title: 'QA & Launch', dueDate: '2026-06-30', completed: false },
    ],
    createdAt: '2025-05-20T10:00:00Z',
  },
  {
    id: 'proj-002',
    name: 'Mobile App v2.0',
    description: 'Major version update for the mobile application including offline support, push notifications, and a redesigned navigation flow.',
    status: 'active',
    progress: 40,
    budget: 200000,
    spent: 80000,
    startDate: '2025-09-01',
    endDate: '2026-08-31',
    teamMembers: ['usr-001', 'usr-002', 'usr-004', 'usr-007'],
    milestones: [
      { id: 'ms-005', title: 'Requirements Finalized', dueDate: '2025-10-01', completed: true },
      { id: 'ms-006', title: 'Alpha Release', dueDate: '2026-02-28', completed: true },
      { id: 'ms-007', title: 'Beta Testing', dueDate: '2026-05-30', completed: false },
      { id: 'ms-008', title: 'Production Release', dueDate: '2026-08-31', completed: false },
    ],
    createdAt: '2025-08-15T14:00:00Z',
  },
  {
    id: 'proj-003',
    name: 'Data Analytics Platform',
    description: 'Build an internal analytics dashboard for real-time business intelligence, reporting, and data visualization.',
    status: 'active',
    progress: 25,
    budget: 300000,
    spent: 75000,
    startDate: '2025-11-01',
    endDate: '2026-10-31',
    teamMembers: ['usr-001', 'usr-004', 'usr-007'],
    milestones: [
      { id: 'ms-009', title: 'Data Pipeline Architecture', dueDate: '2025-12-15', completed: true },
      { id: 'ms-010', title: 'Core Dashboard MVP', dueDate: '2026-04-30', completed: false },
      { id: 'ms-011', title: 'Advanced Reporting Module', dueDate: '2026-08-15', completed: false },
      { id: 'ms-012', title: 'Full Rollout', dueDate: '2026-10-31', completed: false },
    ],
    createdAt: '2025-10-20T09:00:00Z',
  },
  {
    id: 'proj-004',
    name: 'Customer Portal',
    description: 'Self-service customer portal for account management, billing, support tickets, and knowledge base access.',
    status: 'completed',
    progress: 100,
    budget: 120000,
    spent: 115000,
    startDate: '2024-06-01',
    endDate: '2025-03-31',
    teamMembers: ['usr-002', 'usr-003', 'usr-006'],
    milestones: [
      { id: 'ms-013', title: 'Portal Design', dueDate: '2024-08-01', completed: true },
      { id: 'ms-014', title: 'Authentication & Accounts', dueDate: '2024-10-15', completed: true },
      { id: 'ms-015', title: 'Billing Integration', dueDate: '2025-01-15', completed: true },
      { id: 'ms-016', title: 'Launch', dueDate: '2025-03-31', completed: true },
    ],
    createdAt: '2024-05-15T11:00:00Z',
  },
  {
    id: 'proj-005',
    name: 'API Gateway Migration',
    description: 'Migrate from monolithic API to a microservices-based API gateway with improved rate limiting, caching, and documentation.',
    status: 'on-hold',
    progress: 15,
    budget: 180000,
    spent: 27000,
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    teamMembers: ['usr-004', 'usr-008'],
    milestones: [
      { id: 'ms-017', title: 'Architecture Review', dueDate: '2025-11-15', completed: true },
      { id: 'ms-018', title: 'Service Decomposition', dueDate: '2026-03-01', completed: false },
      { id: 'ms-019', title: 'Migration Execution', dueDate: '2026-07-01', completed: false },
      { id: 'ms-020', title: 'Decommission Legacy', dueDate: '2026-09-30', completed: false },
    ],
    createdAt: '2025-09-25T08:00:00Z',
  },
  {
    id: 'proj-006',
    name: 'Marketing Campaign Hub',
    description: 'Centralized platform for planning, executing, and tracking multi-channel marketing campaigns with ROI analytics.',
    status: 'cancelled',
    progress: 10,
    budget: 90000,
    spent: 9000,
    startDate: '2025-07-01',
    endDate: '2026-01-31',
    teamMembers: ['usr-002', 'usr-005'],
    milestones: [
      { id: 'ms-021', title: 'Requirements Gathering', dueDate: '2025-08-01', completed: true },
      { id: 'ms-022', title: 'MVP Development', dueDate: '2025-11-01', completed: false },
      { id: 'ms-023', title: 'Campaign Builder', dueDate: '2025-12-15', completed: false },
      { id: 'ms-024', title: 'Launch', dueDate: '2026-01-31', completed: false },
    ],
    createdAt: '2025-06-20T13:00:00Z',
  },
];

// ============================================================================
// TASKS (25)
// ============================================================================
export const tasks: Task[] = [
  {
    id: 'task-001',
    title: 'Design homepage hero section',
    description: 'Create a visually striking hero section with animated elements and a clear call-to-action for the redesigned homepage.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-003',
    projectId: 'proj-001',
    dueDate: '2025-09-15',
    createdAt: '2025-07-01T10:00:00Z',
    updatedAt: '2025-09-10T16:00:00Z',
    tags: ['design', 'homepage', 'ui'],
    comments: [
      { id: 'cmt-001', userId: 'usr-002', content: 'Love the direction! Can we add a subtle parallax effect?', createdAt: '2025-08-20T14:00:00Z' },
      { id: 'cmt-002', userId: 'usr-003', content: 'Good idea, I will incorporate that in the next iteration.', createdAt: '2025-08-21T09:30:00Z' },
    ],
    order: 1,
  },
  {
    id: 'task-002',
    title: 'Implement user authentication flow',
    description: 'Build secure login, registration, password reset, and email verification flows using NextAuth.js.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-004',
    projectId: 'proj-001',
    dueDate: '2025-10-01',
    createdAt: '2025-07-15T08:00:00Z',
    updatedAt: '2025-09-28T11:00:00Z',
    tags: ['backend', 'auth', 'security'],
    comments: [
      { id: 'cmt-003', userId: 'usr-001', content: 'Make sure to add rate limiting to prevent brute force attacks.', createdAt: '2025-08-05T10:00:00Z' },
    ],
    order: 2,
  },
  {
    id: 'task-003',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing, linting, and deployment to staging and production environments.',
    status: 'in-review',
    priority: 'high',
    assigneeId: 'usr-007',
    projectId: 'proj-001',
    dueDate: '2026-03-10',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-03-01T14:00:00Z',
    tags: ['devops', 'ci-cd', 'automation'],
    comments: [
      { id: 'cmt-004', userId: 'usr-004', content: 'Should we include Playwright tests in the pipeline?', createdAt: '2026-02-10T11:00:00Z' },
      { id: 'cmt-005', userId: 'usr-007', content: 'Yes, I have added E2E tests. The pipeline runs in about 8 minutes total.', createdAt: '2026-02-12T09:00:00Z' },
    ],
    order: 3,
  },
  {
    id: 'task-004',
    title: 'Optimize database queries',
    description: 'Profile and optimize slow database queries, add missing indexes, and implement query caching where appropriate.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'usr-004',
    projectId: 'proj-001',
    dueDate: '2026-03-20',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-02T15:00:00Z',
    tags: ['backend', 'database', 'performance'],
    comments: [
      { id: 'cmt-006', userId: 'usr-001', content: 'The product listing query is taking 3s+. Please prioritize that one.', createdAt: '2026-02-15T08:00:00Z' },
    ],
    order: 4,
  },
  {
    id: 'task-005',
    title: 'Create responsive navigation component',
    description: 'Build a responsive sidebar/topbar navigation that adapts seamlessly between desktop, tablet, and mobile viewports.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'usr-006',
    projectId: 'proj-001',
    dueDate: '2025-10-30',
    createdAt: '2025-08-10T09:00:00Z',
    updatedAt: '2025-10-25T17:00:00Z',
    tags: ['frontend', 'responsive', 'navigation'],
    comments: [],
    order: 5,
  },
  {
    id: 'task-006',
    title: 'Implement push notification service',
    description: 'Set up Firebase Cloud Messaging for push notifications with topic subscriptions and deep linking support.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'usr-004',
    projectId: 'proj-002',
    dueDate: '2026-04-15',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z',
    tags: ['mobile', 'notifications', 'firebase'],
    comments: [
      { id: 'cmt-007', userId: 'usr-002', content: 'We need to support both iOS and Android notification channels.', createdAt: '2026-02-01T09:00:00Z' },
    ],
    order: 1,
  },
  {
    id: 'task-007',
    title: 'Design onboarding screens',
    description: 'Create a 4-step onboarding flow with illustrations showing key app features for first-time users.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'usr-003',
    projectId: 'proj-002',
    dueDate: '2026-04-30',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
    tags: ['design', 'mobile', 'onboarding'],
    comments: [],
    order: 2,
  },
  {
    id: 'task-008',
    title: 'Build offline data sync',
    description: 'Implement local SQLite database with conflict resolution strategy for offline-first data synchronization.',
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'usr-004',
    projectId: 'proj-002',
    dueDate: '2026-05-15',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-02-20T09:00:00Z',
    tags: ['mobile', 'offline', 'sync', 'database'],
    comments: [
      { id: 'cmt-008', userId: 'usr-001', content: 'Use a last-write-wins strategy for non-critical data and manual resolution for shared resources.', createdAt: '2026-02-22T14:00:00Z' },
    ],
    order: 3,
  },
  {
    id: 'task-009',
    title: 'Write unit tests for auth module',
    description: 'Achieve 90%+ test coverage for the authentication module including edge cases for token refresh and session management.',
    status: 'in-review',
    priority: 'medium',
    assigneeId: 'usr-007',
    projectId: 'proj-002',
    dueDate: '2026-03-30',
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-03-02T10:00:00Z',
    tags: ['testing', 'auth', 'quality'],
    comments: [
      { id: 'cmt-009', userId: 'usr-007', content: 'Currently at 87% coverage. Working on the edge cases for expired tokens.', createdAt: '2026-03-01T15:00:00Z' },
    ],
    order: 4,
  },
  {
    id: 'task-010',
    title: 'Set up data pipeline infrastructure',
    description: 'Configure Apache Kafka and Spark Streaming for real-time event processing and data transformation.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-004',
    projectId: 'proj-003',
    dueDate: '2025-12-15',
    createdAt: '2025-11-05T09:00:00Z',
    updatedAt: '2025-12-12T17:00:00Z',
    tags: ['data', 'infrastructure', 'streaming'],
    comments: [],
    order: 1,
  },
  {
    id: 'task-011',
    title: 'Build KPI dashboard widgets',
    description: 'Create reusable chart components for revenue, user growth, conversion rates, and retention metrics.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'usr-003',
    projectId: 'proj-003',
    dueDate: '2026-04-01',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z',
    tags: ['frontend', 'charts', 'analytics'],
    comments: [
      { id: 'cmt-010', userId: 'usr-001', content: 'Use Recharts for consistency with our existing component library.', createdAt: '2026-01-15T10:00:00Z' },
    ],
    order: 2,
  },
  {
    id: 'task-012',
    title: 'Implement data export functionality',
    description: 'Allow users to export dashboard data in CSV, Excel, and PDF formats with customizable date ranges and filters.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'usr-004',
    projectId: 'proj-003',
    dueDate: '2026-05-30',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-02-25T10:00:00Z',
    tags: ['backend', 'export', 'reports'],
    comments: [],
    order: 3,
  },
  {
    id: 'task-013',
    title: 'Create user role permissions matrix',
    description: 'Define and implement granular permissions for viewer, editor, and admin roles within the analytics platform.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'usr-001',
    projectId: 'proj-003',
    dueDate: '2026-04-15',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-02-28T09:00:00Z',
    tags: ['security', 'permissions', 'roles'],
    comments: [],
    order: 4,
  },
  {
    id: 'task-014',
    title: 'Migrate REST endpoints to GraphQL',
    description: 'Incrementally migrate top 20 most-used REST endpoints to GraphQL with proper schema documentation.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'usr-004',
    projectId: 'proj-005',
    dueDate: '2026-06-30',
    createdAt: '2025-11-01T09:00:00Z',
    updatedAt: '2025-11-01T09:00:00Z',
    tags: ['backend', 'graphql', 'migration'],
    comments: [
      { id: 'cmt-011', userId: 'usr-008', content: 'Project is on hold pending budget approval for Q2.', createdAt: '2026-01-15T08:00:00Z' },
    ],
    order: 1,
  },
  {
    id: 'task-015',
    title: 'Design email templates',
    description: 'Create responsive HTML email templates for transactional emails: welcome, password reset, order confirmation, and invoices.',
    status: 'done',
    priority: 'low',
    assigneeId: 'usr-003',
    projectId: 'proj-004',
    dueDate: '2024-09-15',
    createdAt: '2024-07-20T09:00:00Z',
    updatedAt: '2024-09-10T16:00:00Z',
    tags: ['design', 'email', 'templates'],
    comments: [],
    order: 1,
  },
  {
    id: 'task-016',
    title: 'Implement search with Elasticsearch',
    description: 'Set up Elasticsearch cluster and implement full-text search with auto-complete, faceted filters, and typo tolerance.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'usr-004',
    projectId: 'proj-001',
    dueDate: '2026-04-01',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-03-02T11:00:00Z',
    tags: ['backend', 'search', 'elasticsearch'],
    comments: [
      { id: 'cmt-012', userId: 'usr-004', content: 'Cluster is up. Working on the indexing pipeline now.', createdAt: '2026-02-28T14:00:00Z' },
    ],
    order: 6,
  },
  {
    id: 'task-017',
    title: 'Accessibility audit and fixes',
    description: 'Run WCAG 2.1 AA compliance audit using axe-core and fix all critical and serious accessibility violations.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'usr-003',
    projectId: 'proj-001',
    dueDate: '2026-05-01',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
    tags: ['accessibility', 'audit', 'compliance'],
    comments: [],
    order: 7,
  },
  {
    id: 'task-018',
    title: 'Integrate payment gateway',
    description: 'Implement Stripe payment integration with support for credit cards, Apple Pay, and Google Pay.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-004',
    projectId: 'proj-004',
    dueDate: '2025-01-15',
    createdAt: '2024-10-01T09:00:00Z',
    updatedAt: '2025-01-10T15:00:00Z',
    tags: ['backend', 'payments', 'stripe'],
    comments: [
      { id: 'cmt-013', userId: 'usr-002', content: 'Stripe webhook integration tested and working in staging.', createdAt: '2025-01-08T11:00:00Z' },
    ],
    order: 2,
  },
  {
    id: 'task-019',
    title: 'Performance load testing',
    description: 'Run load tests simulating 10K concurrent users and document performance bottlenecks and recommendations.',
    status: 'in-review',
    priority: 'medium',
    assigneeId: 'usr-007',
    projectId: 'proj-001',
    dueDate: '2026-03-25',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-03T09:00:00Z',
    tags: ['testing', 'performance', 'load-testing'],
    comments: [
      { id: 'cmt-014', userId: 'usr-007', content: 'Results show P99 latency of 450ms under 10K concurrent users. Within acceptable range.', createdAt: '2026-03-03T09:00:00Z' },
    ],
    order: 8,
  },
  {
    id: 'task-020',
    title: 'Set up monitoring and alerting',
    description: 'Configure Datadog for application monitoring, custom dashboards, and PagerDuty integration for on-call alerts.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'usr-001',
    projectId: 'proj-001',
    dueDate: '2026-03-30',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-03-02T16:00:00Z',
    tags: ['devops', 'monitoring', 'alerting'],
    comments: [],
    order: 9,
  },
  {
    id: 'task-021',
    title: 'Create API documentation',
    description: 'Write comprehensive OpenAPI 3.0 spec and generate interactive documentation using Swagger UI.',
    status: 'todo',
    priority: 'low',
    assigneeId: 'usr-004',
    projectId: 'proj-002',
    dueDate: '2026-06-01',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    tags: ['documentation', 'api', 'swagger'],
    comments: [],
    order: 5,
  },
  {
    id: 'task-022',
    title: 'Implement dark mode',
    description: 'Add system-aware and manual dark mode toggle with smooth CSS transitions and persistent user preference.',
    status: 'in-progress',
    priority: 'low',
    assigneeId: 'usr-006',
    projectId: 'proj-001',
    dueDate: '2026-04-15',
    createdAt: '2026-02-25T08:00:00Z',
    updatedAt: '2026-03-01T14:00:00Z',
    tags: ['frontend', 'dark-mode', 'theming'],
    comments: [
      { id: 'cmt-015', userId: 'usr-003', content: 'I have prepared the color palette tokens for dark mode in the design system.', createdAt: '2026-02-26T10:00:00Z' },
    ],
    order: 10,
  },
  {
    id: 'task-023',
    title: 'Migrate to React Server Components',
    description: 'Refactor key pages to use React Server Components for improved initial load time and reduced client-side JavaScript.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'usr-001',
    projectId: 'proj-001',
    dueDate: '2026-05-15',
    createdAt: '2026-03-02T09:00:00Z',
    updatedAt: '2026-03-02T09:00:00Z',
    tags: ['frontend', 'react', 'rsc', 'performance'],
    comments: [],
    order: 11,
  },
  {
    id: 'task-024',
    title: 'Build real-time collaboration features',
    description: 'Implement WebSocket-based real-time cursors, presence indicators, and live document editing using Yjs.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'usr-004',
    projectId: 'proj-003',
    dueDate: '2026-07-01',
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: '2026-03-01T11:00:00Z',
    tags: ['backend', 'realtime', 'websocket', 'collaboration'],
    comments: [],
    order: 5,
  },
  {
    id: 'task-025',
    title: 'Internationalization setup',
    description: 'Configure next-intl for multi-language support starting with English, Spanish, French, and German translations.',
    status: 'todo',
    priority: 'low',
    assigneeId: 'usr-003',
    projectId: 'proj-002',
    dueDate: '2026-07-15',
    createdAt: '2026-03-03T08:00:00Z',
    updatedAt: '2026-03-03T08:00:00Z',
    tags: ['frontend', 'i18n', 'localization'],
    comments: [],
    order: 6,
  },
];

// ============================================================================
// PRODUCTS (15)
// ============================================================================
export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Ergonomic Standing Desk',
    description: 'Height-adjustable standing desk with memory presets, cable management tray, and bamboo desktop surface.',
    price: 599.99,
    stock: 45,
    category: 'Furniture',
    sku: 'FURN-DESK-001',
    image: '/products/standing-desk.jpg',
    status: 'in-stock',
    createdAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with 40-hour battery life, active noise cancellation, and multipoint Bluetooth.',
    price: 349.99,
    stock: 120,
    category: 'Electronics',
    sku: 'ELEC-HEAD-001',
    image: '/products/headphones.jpg',
    status: 'in-stock',
    createdAt: '2024-07-20T09:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Mechanical Keyboard',
    description: 'Hot-swappable mechanical keyboard with RGB backlighting, PBT keycaps, and gasket-mount construction.',
    price: 179.99,
    stock: 8,
    category: 'Electronics',
    sku: 'ELEC-KEYB-001',
    image: '/products/keyboard.jpg',
    status: 'low-stock',
    createdAt: '2024-08-10T11:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Ultrawide Monitor 34"',
    description: '34-inch curved ultrawide monitor with 165Hz refresh rate, 1ms response time, and USB-C docking.',
    price: 799.99,
    stock: 22,
    category: 'Electronics',
    sku: 'ELEC-MNTR-001',
    image: '/products/monitor.jpg',
    status: 'in-stock',
    createdAt: '2024-09-05T08:00:00Z',
  },
  {
    id: 'prod-005',
    name: 'Ergonomic Office Chair',
    description: 'Fully adjustable office chair with lumbar support, headrest, 4D armrests, and breathable mesh back.',
    price: 449.99,
    stock: 0,
    category: 'Furniture',
    sku: 'FURN-CHAR-001',
    image: '/products/office-chair.jpg',
    status: 'out-of-stock',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'USB-C Docking Station',
    description: 'Thunderbolt 4 docking station with dual 4K display output, 96W power delivery, and 10Gbps data transfer.',
    price: 249.99,
    stock: 67,
    category: 'Accessories',
    sku: 'ACCS-DOCK-001',
    image: '/products/docking-station.jpg',
    status: 'in-stock',
    createdAt: '2024-10-12T09:00:00Z',
  },
  {
    id: 'prod-007',
    name: 'Webcam 4K Pro',
    description: 'Professional 4K webcam with auto-framing, built-in ring light, and dual noise-cancelling microphones.',
    price: 199.99,
    stock: 5,
    category: 'Electronics',
    sku: 'ELEC-WCAM-001',
    image: '/products/webcam.jpg',
    status: 'low-stock',
    createdAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'prod-008',
    name: 'Desk Lamp LED',
    description: 'Smart LED desk lamp with adjustable color temperature, brightness levels, and USB charging port.',
    price: 79.99,
    stock: 200,
    category: 'Lighting',
    sku: 'LGHT-LAMP-001',
    image: '/products/desk-lamp.jpg',
    status: 'in-stock',
    createdAt: '2024-08-25T08:00:00Z',
  },
  {
    id: 'prod-009',
    name: 'Wireless Mouse',
    description: 'Ergonomic vertical wireless mouse with adjustable DPI, silent clicks, and rechargeable battery.',
    price: 69.99,
    stock: 150,
    category: 'Accessories',
    sku: 'ACCS-MOUS-001',
    image: '/products/wireless-mouse.jpg',
    status: 'in-stock',
    createdAt: '2024-07-15T11:00:00Z',
  },
  {
    id: 'prod-010',
    name: 'Cable Management Kit',
    description: 'Complete cable management set with clips, sleeves, ties, and under-desk cable tray.',
    price: 34.99,
    stock: 300,
    category: 'Accessories',
    sku: 'ACCS-CBLE-001',
    image: '/products/cable-kit.jpg',
    status: 'in-stock',
    createdAt: '2024-09-20T09:00:00Z',
  },
  {
    id: 'prod-011',
    name: 'Laptop Stand Adjustable',
    description: 'Aluminum laptop stand with 360-degree rotation, adjustable height, and ventilation design.',
    price: 59.99,
    stock: 3,
    category: 'Accessories',
    sku: 'ACCS-STND-001',
    image: '/products/laptop-stand.jpg',
    status: 'low-stock',
    createdAt: '2024-10-30T10:00:00Z',
  },
  {
    id: 'prod-012',
    name: 'Whiteboard 48x36',
    description: 'Magnetic dry-erase whiteboard with aluminum frame, marker tray, and wall mounting hardware.',
    price: 129.99,
    stock: 18,
    category: 'Office Supplies',
    sku: 'OFSP-WBRD-001',
    image: '/products/whiteboard.jpg',
    status: 'in-stock',
    createdAt: '2024-11-15T08:00:00Z',
  },
  {
    id: 'prod-013',
    name: 'Portable Projector',
    description: 'Compact 1080p projector with built-in speakers, Wi-Fi casting, and 3-hour battery for presentations.',
    price: 399.99,
    stock: 0,
    category: 'Electronics',
    sku: 'ELEC-PROJ-001',
    image: '/products/projector.jpg',
    status: 'out-of-stock',
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'prod-014',
    name: 'Noise Machine',
    description: 'White noise machine with 30 sound profiles, timer function, and portable design for focused work.',
    price: 49.99,
    stock: 85,
    category: 'Wellness',
    sku: 'WELL-NOIS-001',
    image: '/products/noise-machine.jpg',
    status: 'in-stock',
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: 'prod-015',
    name: 'Monitor Light Bar',
    description: 'Asymmetric LED monitor light bar with auto-dimming sensor, adjustable color temperature, and zero screen glare.',
    price: 89.99,
    stock: 42,
    category: 'Lighting',
    sku: 'LGHT-MBAR-001',
    image: '/products/monitor-light.jpg',
    status: 'in-stock',
    createdAt: '2025-03-01T08:00:00Z',
  },
];

// ============================================================================
// ORDERS (20)
// ============================================================================
export const orders: Order[] = [
  {
    id: 'ord-001',
    userId: 'usr-001',
    customerName: 'Sarah Chen',
    items: [
      { productId: 'prod-001', productName: 'Ergonomic Standing Desk', quantity: 1, price: 599.99 },
      { productId: 'prod-010', productName: 'Cable Management Kit', quantity: 2, price: 34.99 },
    ],
    total: 669.97,
    status: 'delivered',
    date: '2025-11-15T10:30:00Z',
    shippingAddress: '123 Tech Lane, San Francisco, CA 94105',
  },
  {
    id: 'ord-002',
    userId: 'usr-002',
    customerName: 'James Wilson',
    items: [
      { productId: 'prod-002', productName: 'Wireless Noise-Cancelling Headphones', quantity: 1, price: 349.99 },
    ],
    total: 349.99,
    status: 'delivered',
    date: '2025-12-01T14:00:00Z',
    shippingAddress: '456 Product Ave, New York, NY 10001',
  },
  {
    id: 'ord-003',
    userId: 'usr-003',
    customerName: 'Maria Garcia',
    items: [
      { productId: 'prod-004', productName: 'Ultrawide Monitor 34"', quantity: 1, price: 799.99 },
      { productId: 'prod-015', productName: 'Monitor Light Bar', quantity: 1, price: 89.99 },
    ],
    total: 889.98,
    status: 'delivered',
    date: '2025-12-10T09:15:00Z',
    shippingAddress: '789 Design Blvd, Austin, TX 73301',
  },
  {
    id: 'ord-004',
    userId: 'usr-004',
    customerName: 'David Kim',
    items: [
      { productId: 'prod-003', productName: 'Mechanical Keyboard', quantity: 1, price: 179.99 },
      { productId: 'prod-009', productName: 'Wireless Mouse', quantity: 1, price: 69.99 },
      { productId: 'prod-006', productName: 'USB-C Docking Station', quantity: 1, price: 249.99 },
    ],
    total: 499.97,
    status: 'delivered',
    date: '2026-01-05T11:00:00Z',
    shippingAddress: '321 Code St, Seattle, WA 98101',
  },
  {
    id: 'ord-005',
    userId: 'usr-005',
    customerName: 'Emily Johnson',
    items: [
      { productId: 'prod-008', productName: 'Desk Lamp LED', quantity: 2, price: 79.99 },
      { productId: 'prod-014', productName: 'Noise Machine', quantity: 1, price: 49.99 },
    ],
    total: 209.97,
    status: 'shipped',
    date: '2026-02-20T08:30:00Z',
    shippingAddress: '654 Marketing Dr, Chicago, IL 60601',
  },
  {
    id: 'ord-006',
    userId: 'usr-007',
    customerName: 'Rachel Patel',
    items: [
      { productId: 'prod-011', productName: 'Laptop Stand Adjustable', quantity: 1, price: 59.99 },
    ],
    total: 59.99,
    status: 'delivered',
    date: '2026-01-18T15:45:00Z',
    shippingAddress: '987 QA Lane, Denver, CO 80201',
  },
  {
    id: 'ord-007',
    userId: 'usr-001',
    customerName: 'Sarah Chen',
    items: [
      { productId: 'prod-007', productName: 'Webcam 4K Pro', quantity: 2, price: 199.99 },
    ],
    total: 399.98,
    status: 'processing',
    date: '2026-03-01T10:00:00Z',
    shippingAddress: '123 Tech Lane, San Francisco, CA 94105',
  },
  {
    id: 'ord-008',
    userId: 'usr-006',
    customerName: 'Alex Thompson',
    items: [
      { productId: 'prod-001', productName: 'Ergonomic Standing Desk', quantity: 1, price: 599.99 },
      { productId: 'prod-005', productName: 'Ergonomic Office Chair', quantity: 1, price: 449.99 },
    ],
    total: 1049.98,
    status: 'cancelled',
    date: '2025-12-20T13:00:00Z',
    shippingAddress: '159 Frontend Rd, Portland, OR 97201',
  },
  {
    id: 'ord-009',
    userId: 'usr-002',
    customerName: 'James Wilson',
    items: [
      { productId: 'prod-012', productName: 'Whiteboard 48x36', quantity: 3, price: 129.99 },
    ],
    total: 389.97,
    status: 'delivered',
    date: '2026-01-25T09:30:00Z',
    shippingAddress: '456 Product Ave, New York, NY 10001',
  },
  {
    id: 'ord-010',
    userId: 'usr-003',
    customerName: 'Maria Garcia',
    items: [
      { productId: 'prod-003', productName: 'Mechanical Keyboard', quantity: 1, price: 179.99 },
      { productId: 'prod-010', productName: 'Cable Management Kit', quantity: 1, price: 34.99 },
    ],
    total: 214.98,
    status: 'shipped',
    date: '2026-02-28T16:00:00Z',
    shippingAddress: '789 Design Blvd, Austin, TX 73301',
  },
  {
    id: 'ord-011',
    userId: 'usr-004',
    customerName: 'David Kim',
    items: [
      { productId: 'prod-013', productName: 'Portable Projector', quantity: 1, price: 399.99 },
    ],
    total: 399.99,
    status: 'pending',
    date: '2026-03-03T08:00:00Z',
    shippingAddress: '321 Code St, Seattle, WA 98101',
  },
  {
    id: 'ord-012',
    userId: 'usr-005',
    customerName: 'Emily Johnson',
    items: [
      { productId: 'prod-002', productName: 'Wireless Noise-Cancelling Headphones', quantity: 3, price: 349.99 },
    ],
    total: 1049.97,
    status: 'processing',
    date: '2026-03-02T11:30:00Z',
    shippingAddress: '654 Marketing Dr, Chicago, IL 60601',
  },
  {
    id: 'ord-013',
    userId: 'usr-008',
    customerName: 'Michael Brown',
    items: [
      { productId: 'prod-006', productName: 'USB-C Docking Station', quantity: 5, price: 249.99 },
      { productId: 'prod-010', productName: 'Cable Management Kit', quantity: 5, price: 34.99 },
    ],
    total: 1424.90,
    status: 'delivered',
    date: '2025-10-30T10:00:00Z',
    shippingAddress: '753 Ops Center, Boston, MA 02101',
  },
  {
    id: 'ord-014',
    userId: 'usr-007',
    customerName: 'Rachel Patel',
    items: [
      { productId: 'prod-004', productName: 'Ultrawide Monitor 34"', quantity: 1, price: 799.99 },
      { productId: 'prod-011', productName: 'Laptop Stand Adjustable', quantity: 1, price: 59.99 },
      { productId: 'prod-015', productName: 'Monitor Light Bar', quantity: 1, price: 89.99 },
    ],
    total: 949.97,
    status: 'shipped',
    date: '2026-02-25T14:00:00Z',
    shippingAddress: '987 QA Lane, Denver, CO 80201',
  },
  {
    id: 'ord-015',
    userId: 'usr-001',
    customerName: 'Sarah Chen',
    items: [
      { productId: 'prod-014', productName: 'Noise Machine', quantity: 1, price: 49.99 },
      { productId: 'prod-008', productName: 'Desk Lamp LED', quantity: 1, price: 79.99 },
    ],
    total: 129.98,
    status: 'delivered',
    date: '2026-01-10T09:00:00Z',
    shippingAddress: '123 Tech Lane, San Francisco, CA 94105',
  },
  {
    id: 'ord-016',
    userId: 'usr-003',
    customerName: 'Maria Garcia',
    items: [
      { productId: 'prod-009', productName: 'Wireless Mouse', quantity: 1, price: 69.99 },
    ],
    total: 69.99,
    status: 'delivered',
    date: '2025-11-28T12:00:00Z',
    shippingAddress: '789 Design Blvd, Austin, TX 73301',
  },
  {
    id: 'ord-017',
    userId: 'usr-002',
    customerName: 'James Wilson',
    items: [
      { productId: 'prod-001', productName: 'Ergonomic Standing Desk', quantity: 1, price: 599.99 },
      { productId: 'prod-005', productName: 'Ergonomic Office Chair', quantity: 1, price: 449.99 },
      { productId: 'prod-010', productName: 'Cable Management Kit', quantity: 1, price: 34.99 },
    ],
    total: 1084.97,
    status: 'delivered',
    date: '2025-09-15T10:00:00Z',
    shippingAddress: '456 Product Ave, New York, NY 10001',
  },
  {
    id: 'ord-018',
    userId: 'usr-004',
    customerName: 'David Kim',
    items: [
      { productId: 'prod-002', productName: 'Wireless Noise-Cancelling Headphones', quantity: 1, price: 349.99 },
      { productId: 'prod-007', productName: 'Webcam 4K Pro', quantity: 1, price: 199.99 },
    ],
    total: 549.98,
    status: 'pending',
    date: '2026-03-04T07:30:00Z',
    shippingAddress: '321 Code St, Seattle, WA 98101',
  },
  {
    id: 'ord-019',
    userId: 'usr-005',
    customerName: 'Emily Johnson',
    items: [
      { productId: 'prod-012', productName: 'Whiteboard 48x36', quantity: 2, price: 129.99 },
      { productId: 'prod-008', productName: 'Desk Lamp LED', quantity: 4, price: 79.99 },
    ],
    total: 579.94,
    status: 'processing',
    date: '2026-03-01T14:20:00Z',
    shippingAddress: '654 Marketing Dr, Chicago, IL 60601',
  },
  {
    id: 'ord-020',
    userId: 'usr-007',
    customerName: 'Rachel Patel',
    items: [
      { productId: 'prod-003', productName: 'Mechanical Keyboard', quantity: 1, price: 179.99 },
      { productId: 'prod-009', productName: 'Wireless Mouse', quantity: 1, price: 69.99 },
    ],
    total: 249.98,
    status: 'pending',
    date: '2026-03-03T16:00:00Z',
    shippingAddress: '987 QA Lane, Denver, CO 80201',
  },
];

// ============================================================================
// INVOICES (15)
// ============================================================================
export const invoices: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'INV-2025-001',
    clientName: 'Acme Corporation',
    clientEmail: 'billing@acme.com',
    items: [
      { description: 'Website Development - Phase 1', quantity: 1, unitPrice: 25000, total: 25000 },
      { description: 'UI/UX Design Services', quantity: 40, unitPrice: 150, total: 6000 },
    ],
    subtotal: 31000,
    tax: 2790,
    total: 33790,
    status: 'paid',
    issueDate: '2025-09-01',
    dueDate: '2025-10-01',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'INV-2025-002',
    clientName: 'TechStart Inc.',
    clientEmail: 'accounts@techstart.io',
    items: [
      { description: 'Mobile App Development - Sprint 1-3', quantity: 1, unitPrice: 45000, total: 45000 },
      { description: 'Project Management', quantity: 60, unitPrice: 125, total: 7500 },
    ],
    subtotal: 52500,
    tax: 4725,
    total: 57225,
    status: 'paid',
    issueDate: '2025-10-15',
    dueDate: '2025-11-15',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'INV-2025-003',
    clientName: 'Global Retail Solutions',
    clientEmail: 'finance@globalretail.com',
    items: [
      { description: 'E-commerce Platform Setup', quantity: 1, unitPrice: 35000, total: 35000 },
      { description: 'Payment Gateway Integration', quantity: 1, unitPrice: 8000, total: 8000 },
      { description: 'Staff Training Sessions', quantity: 3, unitPrice: 2000, total: 6000 },
    ],
    subtotal: 49000,
    tax: 4410,
    total: 53410,
    status: 'paid',
    issueDate: '2025-11-01',
    dueDate: '2025-12-01',
  },
  {
    id: 'inv-004',
    invoiceNumber: 'INV-2025-004',
    clientName: 'HealthFirst Medical',
    clientEmail: 'ap@healthfirst.org',
    items: [
      { description: 'Patient Portal Development', quantity: 1, unitPrice: 60000, total: 60000 },
      { description: 'HIPAA Compliance Consulting', quantity: 20, unitPrice: 250, total: 5000 },
    ],
    subtotal: 65000,
    tax: 5850,
    total: 70850,
    status: 'pending',
    issueDate: '2026-01-15',
    dueDate: '2026-02-15',
  },
  {
    id: 'inv-005',
    invoiceNumber: 'INV-2026-001',
    clientName: 'EduLearn Platform',
    clientEmail: 'billing@edulearn.com',
    items: [
      { description: 'LMS Core Development', quantity: 1, unitPrice: 40000, total: 40000 },
      { description: 'Video Streaming Integration', quantity: 1, unitPrice: 12000, total: 12000 },
    ],
    subtotal: 52000,
    tax: 4680,
    total: 56680,
    status: 'overdue',
    issueDate: '2025-12-01',
    dueDate: '2026-01-01',
  },
  {
    id: 'inv-006',
    invoiceNumber: 'INV-2026-002',
    clientName: 'Acme Corporation',
    clientEmail: 'billing@acme.com',
    items: [
      { description: 'Website Development - Phase 2', quantity: 1, unitPrice: 30000, total: 30000 },
      { description: 'SEO Optimization Package', quantity: 1, unitPrice: 5000, total: 5000 },
    ],
    subtotal: 35000,
    tax: 3150,
    total: 38150,
    status: 'pending',
    issueDate: '2026-02-01',
    dueDate: '2026-03-01',
  },
  {
    id: 'inv-007',
    invoiceNumber: 'INV-2026-003',
    clientName: 'FinServ Analytics',
    clientEmail: 'payable@finserv.com',
    items: [
      { description: 'Analytics Dashboard Development', quantity: 1, unitPrice: 55000, total: 55000 },
      { description: 'Data Migration Services', quantity: 1, unitPrice: 8000, total: 8000 },
    ],
    subtotal: 63000,
    tax: 5670,
    total: 68670,
    status: 'pending',
    issueDate: '2026-02-15',
    dueDate: '2026-03-15',
  },
  {
    id: 'inv-008',
    invoiceNumber: 'INV-2026-004',
    clientName: 'GreenEnergy Co.',
    clientEmail: 'accounts@greenenergy.io',
    items: [
      { description: 'IoT Dashboard Development', quantity: 1, unitPrice: 45000, total: 45000 },
      { description: 'Real-time Data Processing Setup', quantity: 1, unitPrice: 15000, total: 15000 },
      { description: 'Monthly Maintenance (3 months)', quantity: 3, unitPrice: 3000, total: 9000 },
    ],
    subtotal: 69000,
    tax: 6210,
    total: 75210,
    status: 'pending',
    issueDate: '2026-03-01',
    dueDate: '2026-04-01',
  },
  {
    id: 'inv-009',
    invoiceNumber: 'INV-2026-005',
    clientName: 'Metro Logistics',
    clientEmail: 'finance@metrologistics.com',
    items: [
      { description: 'Fleet Management System', quantity: 1, unitPrice: 70000, total: 70000 },
      { description: 'GPS Integration Module', quantity: 1, unitPrice: 12000, total: 12000 },
    ],
    subtotal: 82000,
    tax: 7380,
    total: 89380,
    status: 'overdue',
    issueDate: '2025-11-15',
    dueDate: '2025-12-15',
  },
  {
    id: 'inv-010',
    invoiceNumber: 'INV-2026-006',
    clientName: 'CloudNine SaaS',
    clientEmail: 'billing@cloudnine.io',
    items: [
      { description: 'Multi-tenant Platform Setup', quantity: 1, unitPrice: 50000, total: 50000 },
      { description: 'Authentication & SSO', quantity: 1, unitPrice: 10000, total: 10000 },
    ],
    subtotal: 60000,
    tax: 5400,
    total: 65400,
    status: 'paid',
    issueDate: '2026-01-10',
    dueDate: '2026-02-10',
  },
  {
    id: 'inv-011',
    invoiceNumber: 'INV-2026-007',
    clientName: 'RetailMax Group',
    clientEmail: 'ap@retailmax.com',
    items: [
      { description: 'POS System Development', quantity: 1, unitPrice: 35000, total: 35000 },
      { description: 'Inventory Sync Module', quantity: 1, unitPrice: 8000, total: 8000 },
      { description: 'Staff Training (on-site)', quantity: 2, unitPrice: 3000, total: 6000 },
    ],
    subtotal: 49000,
    tax: 4410,
    total: 53410,
    status: 'paid',
    issueDate: '2025-12-15',
    dueDate: '2026-01-15',
  },
  {
    id: 'inv-012',
    invoiceNumber: 'INV-2026-008',
    clientName: 'TechStart Inc.',
    clientEmail: 'accounts@techstart.io',
    items: [
      { description: 'Mobile App Development - Sprint 4-6', quantity: 1, unitPrice: 45000, total: 45000 },
      { description: 'Push Notification Service', quantity: 1, unitPrice: 6000, total: 6000 },
    ],
    subtotal: 51000,
    tax: 4590,
    total: 55590,
    status: 'pending',
    issueDate: '2026-03-01',
    dueDate: '2026-04-01',
  },
  {
    id: 'inv-013',
    invoiceNumber: 'INV-2026-009',
    clientName: 'HealthFirst Medical',
    clientEmail: 'ap@healthfirst.org',
    items: [
      { description: 'Telemedicine Module', quantity: 1, unitPrice: 40000, total: 40000 },
      { description: 'EHR Integration', quantity: 1, unitPrice: 18000, total: 18000 },
    ],
    subtotal: 58000,
    tax: 5220,
    total: 63220,
    status: 'cancelled',
    issueDate: '2026-02-20',
    dueDate: '2026-03-20',
  },
  {
    id: 'inv-014',
    invoiceNumber: 'INV-2026-010',
    clientName: 'Global Retail Solutions',
    clientEmail: 'finance@globalretail.com',
    items: [
      { description: 'Mobile Commerce App', quantity: 1, unitPrice: 55000, total: 55000 },
      { description: 'Payment Processing Update', quantity: 1, unitPrice: 7000, total: 7000 },
    ],
    subtotal: 62000,
    tax: 5580,
    total: 67580,
    status: 'paid',
    issueDate: '2026-01-20',
    dueDate: '2026-02-20',
  },
  {
    id: 'inv-015',
    invoiceNumber: 'INV-2026-011',
    clientName: 'EduLearn Platform',
    clientEmail: 'billing@edulearn.com',
    items: [
      { description: 'Assessment Engine', quantity: 1, unitPrice: 25000, total: 25000 },
      { description: 'Reporting Dashboard', quantity: 1, unitPrice: 10000, total: 10000 },
      { description: 'Content Management System', quantity: 1, unitPrice: 8000, total: 8000 },
    ],
    subtotal: 43000,
    tax: 3870,
    total: 46870,
    status: 'pending',
    issueDate: '2026-03-02',
    dueDate: '2026-04-02',
  },
];

// ============================================================================
// TRANSACTIONS (30)
// ============================================================================
export const transactions: Transaction[] = [
  { id: 'txn-001', type: 'income', amount: 33790, currency: 'USD', category: 'Project Revenue', description: 'Payment from Acme Corporation - Website Phase 1', date: '2025-09-28T10:00:00Z', status: 'completed', reference: 'PAY-ACM-001' },
  { id: 'txn-002', type: 'expense', amount: 12500, currency: 'USD', category: 'Payroll', description: 'Engineering team payroll - September 2025', date: '2025-09-30T09:00:00Z', status: 'completed', reference: 'PAY-EMP-SEP25' },
  { id: 'txn-003', type: 'income', amount: 57225, currency: 'USD', category: 'Project Revenue', description: 'Payment from TechStart Inc. - Mobile App Sprint 1-3', date: '2025-11-10T14:00:00Z', status: 'completed', reference: 'PAY-TSI-001' },
  { id: 'txn-004', type: 'expense', amount: 4500, currency: 'USD', category: 'Software Licenses', description: 'Annual Figma Enterprise license renewal', date: '2025-11-15T08:00:00Z', status: 'completed', reference: 'LIC-FIG-2025' },
  { id: 'txn-005', type: 'expense', amount: 8200, currency: 'USD', category: 'Cloud Infrastructure', description: 'AWS monthly invoice - November 2025', date: '2025-12-01T10:00:00Z', status: 'completed', reference: 'AWS-NOV-2025' },
  { id: 'txn-006', type: 'income', amount: 53410, currency: 'USD', category: 'Project Revenue', description: 'Payment from Global Retail Solutions - E-commerce', date: '2025-11-28T11:00:00Z', status: 'completed', reference: 'PAY-GRS-001' },
  { id: 'txn-007', type: 'transfer', amount: 50000, currency: 'USD', category: 'Internal Transfer', description: 'Transfer to savings account for Q1 taxes', date: '2025-12-15T09:00:00Z', status: 'completed', reference: 'TRF-TAX-Q1' },
  { id: 'txn-008', type: 'expense', amount: 12500, currency: 'USD', category: 'Payroll', description: 'Engineering team payroll - December 2025', date: '2025-12-31T09:00:00Z', status: 'completed', reference: 'PAY-EMP-DEC25' },
  { id: 'txn-009', type: 'expense', amount: 3200, currency: 'USD', category: 'Marketing', description: 'Google Ads campaign - Q4 2025', date: '2025-12-28T16:00:00Z', status: 'completed', reference: 'MKT-GAD-Q425' },
  { id: 'txn-010', type: 'income', amount: 65400, currency: 'USD', category: 'Project Revenue', description: 'Payment from CloudNine SaaS - Platform Setup', date: '2026-02-08T10:00:00Z', status: 'completed', reference: 'PAY-CN9-001' },
  { id: 'txn-011', type: 'expense', amount: 8500, currency: 'USD', category: 'Cloud Infrastructure', description: 'AWS monthly invoice - January 2026', date: '2026-02-01T10:00:00Z', status: 'completed', reference: 'AWS-JAN-2026' },
  { id: 'txn-012', type: 'income', amount: 53410, currency: 'USD', category: 'Project Revenue', description: 'Payment from RetailMax Group - POS System', date: '2026-01-12T14:00:00Z', status: 'completed', reference: 'PAY-RMX-001' },
  { id: 'txn-013', type: 'expense', amount: 12500, currency: 'USD', category: 'Payroll', description: 'Engineering team payroll - January 2026', date: '2026-01-31T09:00:00Z', status: 'completed', reference: 'PAY-EMP-JAN26' },
  { id: 'txn-014', type: 'expense', amount: 6200, currency: 'USD', category: 'Software Licenses', description: 'GitHub Enterprise, Jira, and Slack annual licenses', date: '2026-01-05T09:00:00Z', status: 'completed', reference: 'LIC-DEV-2026' },
  { id: 'txn-015', type: 'income', amount: 67580, currency: 'USD', category: 'Project Revenue', description: 'Payment from Global Retail Solutions - Mobile Commerce', date: '2026-02-18T10:00:00Z', status: 'completed', reference: 'PAY-GRS-002' },
  { id: 'txn-016', type: 'transfer', amount: 75000, currency: 'USD', category: 'Internal Transfer', description: 'Transfer to investment fund', date: '2026-01-20T09:00:00Z', status: 'completed', reference: 'TRF-INV-JAN26' },
  { id: 'txn-017', type: 'expense', amount: 8800, currency: 'USD', category: 'Cloud Infrastructure', description: 'AWS monthly invoice - February 2026', date: '2026-03-01T10:00:00Z', status: 'completed', reference: 'AWS-FEB-2026' },
  { id: 'txn-018', type: 'expense', amount: 12500, currency: 'USD', category: 'Payroll', description: 'Engineering team payroll - February 2026', date: '2026-02-28T09:00:00Z', status: 'completed', reference: 'PAY-EMP-FEB26' },
  { id: 'txn-019', type: 'expense', amount: 5600, currency: 'USD', category: 'Marketing', description: 'LinkedIn Ads and content marketing - February', date: '2026-02-25T15:00:00Z', status: 'completed', reference: 'MKT-LNK-FEB26' },
  { id: 'txn-020', type: 'income', amount: 70850, currency: 'USD', category: 'Project Revenue', description: 'Payment from HealthFirst Medical - Patient Portal', date: '2026-02-20T10:00:00Z', status: 'pending', reference: 'PAY-HFM-001' },
  { id: 'txn-021', type: 'expense', amount: 1500, currency: 'USD', category: 'Training', description: 'Team conference tickets - ReactConf 2026', date: '2026-02-15T08:00:00Z', status: 'completed', reference: 'TRN-CONF-001' },
  { id: 'txn-022', type: 'expense', amount: 4200, currency: 'USD', category: 'Insurance', description: 'Business liability insurance - Q1 2026', date: '2026-01-15T09:00:00Z', status: 'completed', reference: 'INS-Q1-2026' },
  { id: 'txn-023', type: 'income', amount: 38150, currency: 'USD', category: 'Project Revenue', description: 'Partial payment from Acme Corporation - Phase 2', date: '2026-03-01T10:00:00Z', status: 'pending', reference: 'PAY-ACM-002' },
  { id: 'txn-024', type: 'transfer', amount: 30000, currency: 'USD', category: 'Internal Transfer', description: 'Transfer to operating reserve fund', date: '2026-03-01T09:00:00Z', status: 'completed', reference: 'TRF-RES-MAR26' },
  { id: 'txn-025', type: 'expense', amount: 3800, currency: 'USD', category: 'Professional Services', description: 'Legal consultation for contract review', date: '2026-02-18T14:00:00Z', status: 'completed', reference: 'PRO-LEG-001' },
  { id: 'txn-026', type: 'income', amount: 68670, currency: 'USD', category: 'Project Revenue', description: 'Payment from FinServ Analytics - Dashboard', date: '2026-03-02T11:00:00Z', status: 'pending', reference: 'PAY-FSA-001' },
  { id: 'txn-027', type: 'expense', amount: 950, currency: 'USD', category: 'Utilities', description: 'Office internet and phone service - February', date: '2026-02-28T12:00:00Z', status: 'completed', reference: 'UTL-FEB-2026' },
  { id: 'txn-028', type: 'income', amount: 75210, currency: 'USD', category: 'Project Revenue', description: 'Payment from GreenEnergy Co. - IoT Dashboard', date: '2026-03-03T10:00:00Z', status: 'pending', reference: 'PAY-GEC-001' },
  { id: 'txn-029', type: 'expense', amount: 2800, currency: 'USD', category: 'Office Supplies', description: 'Quarterly office equipment and supplies order', date: '2026-01-25T09:00:00Z', status: 'completed', reference: 'OFC-Q1-2026' },
  { id: 'txn-030', type: 'expense', amount: 12500, currency: 'USD', category: 'Payroll', description: 'Engineering team payroll - March 2026 (scheduled)', date: '2026-03-31T09:00:00Z', status: 'pending', reference: 'PAY-EMP-MAR26' },
];

// ============================================================================
// NOTIFICATIONS (20)
// ============================================================================
export const notifications: Notification[] = [
  { id: 'notif-001', userId: 'usr-001', title: 'New Task Assigned', message: 'You have been assigned "Set up monitoring and alerting" in Website Redesign.', type: 'info', date: '2026-03-03T14:00:00Z', read: false },
  { id: 'notif-002', userId: 'usr-001', title: 'Invoice Overdue', message: 'Invoice INV-2026-001 from EduLearn Platform is 62 days overdue.', type: 'warning', date: '2026-03-03T09:00:00Z', read: false },
  { id: 'notif-003', userId: 'usr-002', title: 'Project Milestone Reached', message: 'Mobile App v2.0 has reached the "Alpha Release" milestone.', type: 'success', date: '2026-02-28T16:00:00Z', read: true },
  { id: 'notif-004', userId: 'usr-003', title: 'Design Review Requested', message: 'David Kim requested a design review for the KPI dashboard widgets.', type: 'info', date: '2026-03-01T10:00:00Z', read: false },
  { id: 'notif-005', userId: 'usr-004', title: 'Build Failed', message: 'CI pipeline failed for branch feature/search-integration. Check logs for details.', type: 'error', date: '2026-03-02T15:30:00Z', read: true },
  { id: 'notif-006', userId: 'usr-004', title: 'Pull Request Approved', message: 'Your PR #247 "Add Elasticsearch indexing pipeline" has been approved by Sarah Chen.', type: 'success', date: '2026-03-02T17:00:00Z', read: true },
  { id: 'notif-007', userId: 'usr-005', title: 'Budget Alert', message: 'Marketing campaign budget has reached 85% utilization for this quarter.', type: 'warning', date: '2026-02-25T11:00:00Z', read: true },
  { id: 'notif-008', userId: 'usr-007', title: 'Test Results Ready', message: 'Load testing report for the Website Redesign project is ready for review.', type: 'info', date: '2026-03-03T09:30:00Z', read: false },
  { id: 'notif-009', userId: 'usr-001', title: 'System Update Scheduled', message: 'Planned maintenance window: March 8, 2026, 2:00 AM - 6:00 AM EST.', type: 'info', date: '2026-03-03T08:00:00Z', read: false },
  { id: 'notif-010', userId: 'usr-002', title: 'New Comment on Task', message: 'Rachel Patel commented on "Write unit tests for auth module".', type: 'info', date: '2026-03-01T15:00:00Z', read: true },
  { id: 'notif-011', userId: 'usr-003', title: 'Task Due Tomorrow', message: 'Task "Build KPI dashboard widgets" is due on April 1, 2026.', type: 'warning', date: '2026-03-03T07:00:00Z', read: false },
  { id: 'notif-012', userId: 'usr-004', title: 'Deployment Successful', message: 'Version 2.4.1 has been successfully deployed to staging environment.', type: 'success', date: '2026-03-02T20:00:00Z', read: true },
  { id: 'notif-013', userId: 'usr-001', title: 'New Team Member', message: 'A new team member request is pending approval for the Data Analytics Platform project.', type: 'info', date: '2026-03-02T13:00:00Z', read: true },
  { id: 'notif-014', userId: 'usr-005', title: 'Report Generated', message: 'Monthly marketing performance report for February 2026 is available.', type: 'success', date: '2026-03-01T06:00:00Z', read: true },
  { id: 'notif-015', userId: 'usr-007', title: 'Security Scan Complete', message: 'Weekly security scan completed. 2 medium-severity vulnerabilities found.', type: 'warning', date: '2026-03-02T04:00:00Z', read: false },
  { id: 'notif-016', userId: 'usr-001', title: 'Payment Received', message: 'Payment of $74,120.00 received from Global Retail Solutions.', type: 'success', date: '2026-02-08T10:30:00Z', read: true },
  { id: 'notif-017', userId: 'usr-002', title: 'Sprint Planning Reminder', message: 'Sprint 12 planning meeting is scheduled for tomorrow at 10:00 AM.', type: 'info', date: '2026-03-03T17:00:00Z', read: false },
  { id: 'notif-018', userId: 'usr-004', title: 'Database Alert', message: 'Database connection pool usage exceeded 80% threshold.', type: 'error', date: '2026-03-03T12:00:00Z', read: false },
  { id: 'notif-019', userId: 'usr-003', title: 'Feedback Received', message: 'Client feedback received for the Customer Portal project designs.', type: 'info', date: '2026-02-27T14:00:00Z', read: true },
  { id: 'notif-020', userId: 'usr-001', title: 'License Expiring', message: 'Your Datadog license expires in 15 days. Please renew to avoid service interruption.', type: 'warning', date: '2026-03-03T06:00:00Z', read: false },
];

// ============================================================================
// ALERTS (10)
// ============================================================================
export const alerts: Alert[] = [
  { id: 'alert-001', title: 'High CPU Usage', message: 'Production server cpu-prod-01 is running at 94% CPU utilization for the last 15 minutes.', severity: 'critical', date: '2026-03-03T14:30:00Z', resolved: false, source: 'Infrastructure Monitoring' },
  { id: 'alert-002', title: 'SSL Certificate Expiring', message: 'SSL certificate for api.company.com expires in 7 days. Auto-renewal has been triggered.', severity: 'high', date: '2026-03-02T08:00:00Z', resolved: false, source: 'Security Scanner' },
  { id: 'alert-003', title: 'Disk Space Warning', message: 'Database server db-primary-01 has only 12% disk space remaining (18 GB of 150 GB).', severity: 'high', date: '2026-03-01T22:00:00Z', resolved: false, source: 'Infrastructure Monitoring' },
  { id: 'alert-004', title: 'Failed Login Attempts', message: '47 failed login attempts detected from IP 203.0.113.42 in the last hour. IP has been temporarily blocked.', severity: 'medium', date: '2026-03-03T11:00:00Z', resolved: true, source: 'Security Scanner' },
  { id: 'alert-005', title: 'API Response Time Degradation', message: 'Average API response time increased from 120ms to 850ms for the /api/products endpoint.', severity: 'high', date: '2026-03-02T16:00:00Z', resolved: true, source: 'Application Monitoring' },
  { id: 'alert-006', title: 'Memory Leak Detected', message: 'Node.js process memory usage has been steadily increasing over the last 6 hours on worker-03.', severity: 'medium', date: '2026-03-03T06:00:00Z', resolved: false, source: 'Application Monitoring' },
  { id: 'alert-007', title: 'Backup Job Failed', message: 'Nightly database backup job failed at 3:15 AM. Error: Connection timeout to backup storage.', severity: 'critical', date: '2026-03-03T03:15:00Z', resolved: true, source: 'Backup System' },
  { id: 'alert-008', title: 'Dependency Vulnerability', message: '3 high-severity CVEs found in production dependencies: lodash, express, jsonwebtoken.', severity: 'high', date: '2026-03-01T10:00:00Z', resolved: false, source: 'Security Scanner' },
  { id: 'alert-009', title: 'Rate Limit Threshold', message: 'API rate limit threshold reached for client ID cli-acme-prod. 95% of hourly quota consumed.', severity: 'low', date: '2026-03-03T13:00:00Z', resolved: false, source: 'API Gateway' },
  { id: 'alert-010', title: 'CDN Cache Hit Ratio Low', message: 'CDN cache hit ratio dropped to 62% (normal: 90%+). Possible cache invalidation issue.', severity: 'medium', date: '2026-03-02T19:00:00Z', resolved: true, source: 'CDN Monitoring' },
];

// ============================================================================
// ACTIVITIES (25)
// ============================================================================
export const activities: Activity[] = [
  { id: 'act-001', userId: 'usr-001', userName: 'Sarah Chen', action: 'created', target: 'Project', details: 'Created project "Data Analytics Platform"', timestamp: '2025-10-20T09:00:00Z' },
  { id: 'act-002', userId: 'usr-004', userName: 'David Kim', action: 'completed', target: 'Task', details: 'Completed "Set up data pipeline infrastructure"', timestamp: '2025-12-12T17:00:00Z' },
  { id: 'act-003', userId: 'usr-003', userName: 'Maria Garcia', action: 'uploaded', target: 'Design', details: 'Uploaded new design mockups for homepage hero section', timestamp: '2025-09-08T14:30:00Z' },
  { id: 'act-004', userId: 'usr-002', userName: 'James Wilson', action: 'approved', target: 'Milestone', details: 'Approved milestone "Alpha Release" for Mobile App v2.0', timestamp: '2026-02-28T16:00:00Z' },
  { id: 'act-005', userId: 'usr-007', userName: 'Rachel Patel', action: 'submitted', target: 'Report', details: 'Submitted load testing report with P99 latency results', timestamp: '2026-03-03T09:00:00Z' },
  { id: 'act-006', userId: 'usr-004', userName: 'David Kim', action: 'deployed', target: 'Release', details: 'Deployed v2.4.1 to staging environment', timestamp: '2026-03-02T20:00:00Z' },
  { id: 'act-007', userId: 'usr-001', userName: 'Sarah Chen', action: 'merged', target: 'Pull Request', details: 'Merged PR #247 "Add Elasticsearch indexing pipeline"', timestamp: '2026-03-02T17:15:00Z' },
  { id: 'act-008', userId: 'usr-005', userName: 'Emily Johnson', action: 'published', target: 'Article', details: 'Published "Q4 2025 Marketing Performance Review"', timestamp: '2026-01-05T10:00:00Z' },
  { id: 'act-009', userId: 'usr-003', userName: 'Maria Garcia', action: 'updated', target: 'Design System', details: 'Updated color palette tokens for dark mode support', timestamp: '2026-02-26T10:00:00Z' },
  { id: 'act-010', userId: 'usr-004', userName: 'David Kim', action: 'opened', target: 'Pull Request', details: 'Opened PR #251 "Optimize product listing query performance"', timestamp: '2026-03-02T11:30:00Z' },
  { id: 'act-011', userId: 'usr-001', userName: 'Sarah Chen', action: 'configured', target: 'Monitoring', details: 'Configured Datadog APM for production services', timestamp: '2026-03-02T16:00:00Z' },
  { id: 'act-012', userId: 'usr-007', userName: 'Rachel Patel', action: 'created', target: 'Test Suite', details: 'Created E2E test suite for authentication flows', timestamp: '2026-02-10T14:00:00Z' },
  { id: 'act-013', userId: 'usr-002', userName: 'James Wilson', action: 'scheduled', target: 'Meeting', details: 'Scheduled Sprint 12 planning meeting for March 4', timestamp: '2026-03-03T17:00:00Z' },
  { id: 'act-014', userId: 'usr-006', userName: 'Alex Thompson', action: 'started', target: 'Task', details: 'Started working on "Implement dark mode"', timestamp: '2026-02-25T08:30:00Z' },
  { id: 'act-015', userId: 'usr-001', userName: 'Sarah Chen', action: 'resolved', target: 'Alert', details: 'Resolved backup job failure by increasing storage connection timeout', timestamp: '2026-03-03T05:30:00Z' },
  { id: 'act-016', userId: 'usr-004', userName: 'David Kim', action: 'fixed', target: 'Bug', details: 'Fixed API response time degradation on /api/products endpoint', timestamp: '2026-03-02T18:00:00Z' },
  { id: 'act-017', userId: 'usr-003', userName: 'Maria Garcia', action: 'reviewed', target: 'Pull Request', details: 'Reviewed PR #249 "Add responsive navigation improvements"', timestamp: '2026-03-01T11:00:00Z' },
  { id: 'act-018', userId: 'usr-005', userName: 'Emily Johnson', action: 'created', target: 'Campaign', details: 'Created LinkedIn Ads campaign for Q1 2026', timestamp: '2026-02-01T09:00:00Z' },
  { id: 'act-019', userId: 'usr-001', userName: 'Sarah Chen', action: 'invoiced', target: 'Client', details: 'Sent invoice INV-2026-010 to HealthFirst Medical for $70,850', timestamp: '2026-03-01T10:00:00Z' },
  { id: 'act-020', userId: 'usr-007', userName: 'Rachel Patel', action: 'updated', target: 'Task', details: 'Updated test coverage for auth module to 87%', timestamp: '2026-03-01T15:00:00Z' },
  { id: 'act-021', userId: 'usr-002', userName: 'James Wilson', action: 'commented', target: 'Task', details: 'Commented on "Implement push notification service"', timestamp: '2026-02-01T09:00:00Z' },
  { id: 'act-022', userId: 'usr-004', userName: 'David Kim', action: 'created', target: 'Branch', details: 'Created branch feature/offline-sync for offline data sync feature', timestamp: '2026-03-01T08:00:00Z' },
  { id: 'act-023', userId: 'usr-001', userName: 'Sarah Chen', action: 'assigned', target: 'Task', details: 'Assigned "Accessibility audit and fixes" to Maria Garcia', timestamp: '2026-03-01T08:00:00Z' },
  { id: 'act-024', userId: 'usr-003', userName: 'Maria Garcia', action: 'completed', target: 'Task', details: 'Completed dark mode color palette tokens in design system', timestamp: '2026-02-28T17:00:00Z' },
  { id: 'act-025', userId: 'usr-008', userName: 'Michael Brown', action: 'paused', target: 'Project', details: 'Put "API Gateway Migration" project on hold pending budget review', timestamp: '2026-01-15T08:00:00Z' },
];

// ============================================================================
// SUPPORT TICKETS (8)
// ============================================================================
export const supportTickets: SupportTicket[] = [
  { id: 'ticket-001', userId: 'usr-003', subject: 'Cannot export dashboard to PDF', description: 'When I try to export the analytics dashboard to PDF, the download starts but the file is corrupted and cannot be opened. Tried in Chrome and Firefox.', status: 'open', priority: 'high', category: 'Bug Report', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' },
  { id: 'ticket-002', userId: 'usr-005', subject: 'Request access to Data Analytics Platform', description: 'I need viewer access to the Data Analytics Platform to monitor marketing campaign performance metrics. My current role does not have access.', status: 'in-progress', priority: 'medium', category: 'Access Request', createdAt: '2026-03-02T14:00:00Z', updatedAt: '2026-03-03T09:00:00Z' },
  { id: 'ticket-003', userId: 'usr-004', subject: 'Staging environment database connection timeout', description: 'The staging database is intermittently timing out with connection pool exhaustion errors. Started happening after the latest deployment yesterday.', status: 'in-progress', priority: 'high', category: 'Infrastructure', createdAt: '2026-03-01T16:00:00Z', updatedAt: '2026-03-02T11:00:00Z' },
  { id: 'ticket-004', userId: 'usr-002', subject: 'Calendar sync not working with Outlook', description: 'Project milestones and deadlines are no longer syncing to my Outlook calendar. The integration was working fine until last week.', status: 'resolved', priority: 'low', category: 'Integration', createdAt: '2026-02-25T09:00:00Z', updatedAt: '2026-02-28T15:00:00Z' },
  { id: 'ticket-005', userId: 'usr-007', subject: 'Need larger CI/CD runner instances', description: 'Our E2E test suite is timing out on the current runner instances. We need to upgrade to larger instances with more memory and CPU for the Playwright tests.', status: 'open', priority: 'medium', category: 'Infrastructure', createdAt: '2026-03-03T08:00:00Z', updatedAt: '2026-03-03T08:00:00Z' },
  { id: 'ticket-006', userId: 'usr-006', subject: 'Dark mode colors inconsistent across pages', description: 'Some pages use the old color tokens when dark mode is enabled. The settings page, profile page, and notification panel all show the wrong background colors.', status: 'open', priority: 'medium', category: 'Bug Report', createdAt: '2026-03-02T10:00:00Z', updatedAt: '2026-03-02T10:00:00Z' },
  { id: 'ticket-007', userId: 'usr-001', subject: 'Two-factor authentication reset', description: 'Lost access to my authenticator app after phone replacement. Need a 2FA reset to regain access to the admin panel on my new device.', status: 'closed', priority: 'high', category: 'Account', createdAt: '2026-02-15T07:00:00Z', updatedAt: '2026-02-15T10:00:00Z' },
  { id: 'ticket-008', userId: 'usr-003', subject: 'Feature request: Figma plugin integration', description: 'It would be very helpful to have a Figma plugin that syncs design tokens and component specs directly to the project management dashboard.', status: 'open', priority: 'low', category: 'Feature Request', createdAt: '2026-02-20T11:00:00Z', updatedAt: '2026-02-20T11:00:00Z' },
];

// ============================================================================
// FAQ (12)
// ============================================================================
export const faqs: FAQ[] = [
  { id: 'faq-001', question: 'How do I create a new project?', answer: 'Navigate to the Projects page and click the "New Project" button in the top right corner. Fill in the project name, description, dates, budget, and assign team members. Click "Create" to finalize.', category: 'Projects' },
  { id: 'faq-002', question: 'How do I assign a task to a team member?', answer: 'Open the task by clicking on it, then use the "Assignee" dropdown to select a team member. You can also drag and drop tasks between columns on the Kanban board to change their status.', category: 'Tasks' },
  { id: 'faq-003', question: 'How do I generate an invoice?', answer: 'Go to the Invoices page and click "Create Invoice". Select the client, add line items with descriptions, quantities, and prices. The subtotal, tax, and total will be calculated automatically. Click "Send" to email the invoice to the client.', category: 'Billing' },
  { id: 'faq-004', question: 'What are the different user roles?', answer: 'There are three roles: Admin (full system access including user management and settings), Manager (can create and manage projects, assign tasks, and view reports), and User (can view assigned tasks, update their status, and access their own data).', category: 'Account' },
  { id: 'faq-005', question: 'How do I reset my password?', answer: 'Click "Forgot Password" on the login page and enter your email address. You will receive a password reset link valid for 24 hours. If you do not receive the email, check your spam folder or contact support.', category: 'Account' },
  { id: 'faq-006', question: 'How do I track project progress?', answer: 'Project progress is automatically calculated based on completed tasks and milestones. You can view the progress bar on the Projects page, or click into a project for detailed milestone tracking and burndown charts.', category: 'Projects' },
  { id: 'faq-007', question: 'Can I export data from the dashboard?', answer: 'Yes, most data views support export in CSV, Excel, and PDF formats. Look for the "Export" button in the top right of any data table. You can customize the date range and columns before exporting.', category: 'General' },
  { id: 'faq-008', question: 'How do notifications work?', answer: 'Notifications are triggered by events like task assignments, due date reminders, comments, and system alerts. You can configure which notifications you receive in Settings > Notifications. Both in-app and email notifications are supported.', category: 'General' },
  { id: 'faq-009', question: 'How do I connect integrations?', answer: 'Navigate to Settings > Integrations to connect third-party tools. We support Slack, GitHub, Jira, Figma, Google Calendar, and Outlook. Click "Connect" next to the desired integration and follow the OAuth authentication flow.', category: 'Integrations' },
  { id: 'faq-010', question: 'What happens when a project is completed?', answer: 'Completed projects are moved to the archive and no longer appear in the active projects list. All tasks, milestones, and data are preserved and can be accessed from the "Completed" tab on the Projects page.', category: 'Projects' },
  { id: 'faq-011', question: 'How do I manage product inventory?', answer: 'The Products page shows current stock levels with color-coded status indicators. Products automatically change to "Low Stock" when inventory drops below the threshold you set, and "Out of Stock" when it reaches zero.', category: 'Products' },
  { id: 'faq-012', question: 'How do I submit a support ticket?', answer: 'Click the "Help" icon in the bottom right corner or navigate to the Support page. Click "New Ticket", fill in the subject, description, category, and priority. Our support team typically responds within 4 business hours.', category: 'Support' },
];

// ============================================================================
// ARTICLES (8)
// ============================================================================
export const articles: Article[] = [
  { id: 'art-001', title: 'Getting Started with Your Project Dashboard', content: 'Welcome to your project management dashboard. This comprehensive guide will walk you through setting up your first project, inviting team members, creating tasks, and tracking progress effectively. Start by navigating to the Projects page where you can create your first project with a name, description, timeline, and budget. Once your project is set up, you can begin adding tasks and assigning them to team members.', excerpt: 'A complete beginner guide to setting up and using your project management dashboard effectively.', author: 'Sarah Chen', category: 'Getting Started', tags: ['onboarding', 'tutorial', 'basics'], publishedAt: '2025-06-15T10:00:00Z', readTime: 8 },
  { id: 'art-002', title: 'Best Practices for Agile Project Management', content: 'Agile project management is all about iterative development and continuous improvement. This article covers sprint planning, daily standups, retrospectives, and how to use the Kanban board effectively. Learn how to break down large features into manageable user stories, estimate effort using story points, and track velocity across sprints to improve predictability.', excerpt: 'Learn how to implement agile methodologies using the dashboard built-in tools for sprint planning and tracking.', author: 'James Wilson', category: 'Best Practices', tags: ['agile', 'scrum', 'kanban', 'productivity'], publishedAt: '2025-08-20T14:00:00Z', readTime: 12 },
  { id: 'art-003', title: 'Understanding Your Financial Dashboard', content: 'The financial dashboard provides a comprehensive view of your organization financial health. Track revenue streams, monitor expenses, manage invoices, and analyze cash flow trends. This guide explains each widget, how to customize date ranges, and how to set up automated financial reports for stakeholders.', excerpt: 'A deep dive into the financial dashboard features including revenue tracking, expense monitoring, and invoicing.', author: 'Emily Johnson', category: 'Finance', tags: ['finance', 'invoices', 'revenue', 'reporting'], publishedAt: '2025-10-05T09:00:00Z', readTime: 10 },
  { id: 'art-004', title: 'Securing Your Workspace: Security Best Practices', content: 'Security is a shared responsibility. This article covers essential security practices including enabling two-factor authentication, managing API keys, setting up IP allowlists, configuring role-based access controls, and understanding the audit log. We also cover how to respond to security alerts and manage vulnerability disclosures.', excerpt: 'Essential security practices for protecting your data and managing access controls in the dashboard.', author: 'Sarah Chen', category: 'Security', tags: ['security', '2fa', 'access-control', 'best-practices'], publishedAt: '2025-12-01T11:00:00Z', readTime: 7 },
  { id: 'art-005', title: 'Automating Your Workflow with Integrations', content: 'Integrate your dashboard with the tools you already use. Connect Slack for real-time notifications, sync with GitHub for automatic task updates when PRs are merged, link Figma for design handoff, and connect your calendar for deadline tracking. This guide walks through each integration step by step.', excerpt: 'Step-by-step guide to connecting Slack, GitHub, Figma, and calendar integrations for automated workflows.', author: 'David Kim', category: 'Integrations', tags: ['integrations', 'automation', 'slack', 'github'], publishedAt: '2026-01-15T10:00:00Z', readTime: 9 },
  { id: 'art-006', title: 'Q4 2025 Marketing Performance Review', content: 'A detailed analysis of our Q4 2025 marketing performance. Digital ad spend increased by 15% with a corresponding 23% increase in qualified leads. Content marketing drove 40% of organic traffic, up from 32% in Q3. Social media engagement grew by 18% across all platforms. This report includes recommendations for Q1 2026 strategy adjustments.', excerpt: 'Comprehensive review of Q4 2025 marketing metrics including ad performance, content ROI, and social engagement.', author: 'Emily Johnson', category: 'Reports', tags: ['marketing', 'analytics', 'quarterly-review', 'performance'], publishedAt: '2026-01-05T10:00:00Z', readTime: 15 },
  { id: 'art-007', title: 'Building Effective Dashboards with Custom Widgets', content: 'Create personalized dashboards that show exactly the data you need. This guide covers how to add, remove, and rearrange widgets, customize chart types and date ranges, set up KPI thresholds with color-coded indicators, and share custom dashboard layouts with your team members.', excerpt: 'Learn to create custom dashboard layouts with widgets tailored to your role and responsibilities.', author: 'Maria Garcia', category: 'Customization', tags: ['dashboard', 'widgets', 'customization', 'data-visualization'], publishedAt: '2026-02-10T08:00:00Z', readTime: 6 },
  { id: 'art-008', title: 'Managing Remote Teams with the Dashboard', content: 'Remote team management requires clear communication and visibility. Use the dashboard activity feed to stay informed about team progress, leverage the real-time presence indicators to see who is online, use time zone overlaps for meeting scheduling, and track individual workload distribution to prevent burnout.', excerpt: 'Tips and strategies for managing distributed teams using the dashboard collaboration and tracking features.', author: 'James Wilson', category: 'Best Practices', tags: ['remote-work', 'team-management', 'collaboration', 'productivity'], publishedAt: '2026-02-28T14:00:00Z', readTime: 11 },
];

// ============================================================================
// CATEGORIES (10)
// ============================================================================
export const categories: Category[] = [
  { id: 'cat-001', name: 'Electronics', description: 'Computer peripherals, monitors, webcams, and other electronic devices for the modern workspace.', slug: 'electronics', itemCount: 5, parentId: null },
  { id: 'cat-002', name: 'Furniture', description: 'Desks, chairs, and other office furniture designed for comfort and productivity.', slug: 'furniture', itemCount: 2, parentId: null },
  { id: 'cat-003', name: 'Accessories', description: 'Docking stations, cable management, laptop stands, and other workspace accessories.', slug: 'accessories', itemCount: 4, parentId: null },
  { id: 'cat-004', name: 'Lighting', description: 'Desk lamps, monitor light bars, and ambient lighting solutions for optimal work environments.', slug: 'lighting', itemCount: 2, parentId: null },
  { id: 'cat-005', name: 'Office Supplies', description: 'Whiteboards, stationery, and essential office supplies for daily operations.', slug: 'office-supplies', itemCount: 1, parentId: null },
  { id: 'cat-006', name: 'Wellness', description: 'Products designed to improve focus, comfort, and well-being in the workplace.', slug: 'wellness', itemCount: 1, parentId: null },
  { id: 'cat-007', name: 'Audio Equipment', description: 'Headphones, speakers, and microphones for meetings and focused work.', slug: 'audio-equipment', itemCount: 1, parentId: 'cat-001' },
  { id: 'cat-008', name: 'Displays', description: 'Monitors, portable displays, and projectors for presentations and multi-screen setups.', slug: 'displays', itemCount: 2, parentId: 'cat-001' },
  { id: 'cat-009', name: 'Input Devices', description: 'Keyboards, mice, trackpads, and other input devices for ergonomic computing.', slug: 'input-devices', itemCount: 2, parentId: 'cat-001' },
  { id: 'cat-010', name: 'Standing Desks', description: 'Height-adjustable desks for alternating between sitting and standing positions.', slug: 'standing-desks', itemCount: 1, parentId: 'cat-002' },
];

// ============================================================================
// DASHBOARD STATS
// ============================================================================
export const dashboardStats: DashboardStats = {
  totalProjects: 6,
  activeTasks: 14,
  teamMembers: 8,
  completionRate: 72.5,
  totalRevenue: 574975,
  pendingInvoices: 6,
  openTickets: 4,
  systemHealth: 96.8,
};
